<?php
return [
    'LAB' => 'Bagian Laboratorium',
    'AKA' => 'Bagian Pelayanan Akademik Pusat',
    'INV' => 'Bagian Sentra Inovasi',
    'PPM' => 'Lembaga Penelitian dan Pengabdian Masyarakat',
    'MHS' => 'Bagian Kemahasiswaan',
    'KUG' => 'Bagian Keuangan',
    'LOG' => 'Bagian Logistik Dan Manajemen Aset',
    'SIF' => 'Bagian Sistem Dan Teknologi Informasi',
    'SDM' => 'Bagian Sumber Daya Manusia',
    'CDC' => 'Bagian Alumni Dan Konseling',
    'PSR' => 'Bagian Pemasaran Dan Admisi',
    'DET' => 'CoE Digital Economic, Tourism and Creative Innovation',
    'HWT' => 'CoE Healthcare and Well Being Technologies',
    'ICT' => 'CoE ICT Infrastructure, Smart Manufacture and Digital Supply Chain',
    'SCV' => 'CoE Sustainability Cities, Village and Food Security',
    'DIR' => 'Direktorat Universitas Telkom',
    'HUM' => 'Bagian Humas, Kerjasama, Dan KUI',
    'SPM' => 'Bagian Penjaminan Mutu, Perencanaan, Dan Pengembangan Pembelajaran',
    'SEK' => 'Bagian Sekretariat Pimpinan, Legal & Internal Audit',
    'BSD' => 'Program Studi S1 Bisnis Digital',
    'RPL' => 'Program Studi S1 Rekayasa Perangkat Lunak',
    'DSA' => 'Program Studi S1 Sains Data',
    'INF' => 'Program Studi S1 Teknik Informatika',
    'DKV' => 'Program Studi S1 Desain Komunikasi Visual',
    'DSP' => 'Program Studi S1 Desain Produk',
    'TTD' => 'Program Studi D3 Teknik Telekomunikasi',
    'SIN' => 'Program Studi S1 Sistem Informasi',
    'TIN' => 'Program Studi S1 Teknik Industri',
    'TLO' => 'Program Studi S1 Teknik Logistik',
    'TPA' => 'Program Studi S1 Teknologi Pangan',
    'BME' => 'Program Studi S1 Teknik Biomedis',
    'TEL' => 'Program Studi S1 Teknik Elektro',
    'TTS' => 'Program Studi S1 Teknik Telekomunikasi',
];
